CodeTheWay/CodeTheWay.Web.Ui/Models/ShippingContainer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeTheWay.Web.Ui.Models
{
    public class ShippingContainer
    {
        public Guid Id { get; set; }
        public int Weight { get; set; }
        public string Destination { get; set; }

    }
}

CodeTheWay/CodeTheWay.Web.Ui/Controllers/ShippingContainerController.cs
using CodeTheWay.Web.Ui.Models;
using CodeTheWay.Web.Ui.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace CodeTheWay.Web.Ui.Controllers
{
    public class ShippingContainerController : Controller
    {
        private IShippingContainerService ShippingContainerService;
        public ShippingContainerController(IShippingContainerService shippingContainerService)
        {
            this.ShippingContainerService = shippingContainerService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await ShippingContainerService.GetShippingContainers());
        }
        public async Task<IActionResult> Create() {
            return View(new ShippingContainer());
        }
        [HttpPost]
        public async Task<IActionResult> Register(ShippingContainer model) {
            if (ModelState.IsValid) {
                var shippingcontainer = await ShippingContainerService.Create(model);
                return RedirectToAction("Index");
            }
            return View("Create", model);
        }

        public async Task<IActionResult> Edit(Guid id) {
            var shippingcontainer = await ShippingContainerService.GetShippingContainer(id);
            return View(shippingcontainer);
        }
        [HttpPost]
        public async Task<IActionResult> Update(ShippingContainer model) {
            if (ModelState.IsValid) {
                var shippingcontainer = await ShippingContainerService.Update(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            var shippingcontainer = await ShippingContainerService.GetShippingContainer(id);
            return View(shippingcontainer);
        }
        public async Task<IActionResult> Delete(Guid id) {
            var shippingcontainer = await ShippingContainerService.GetShippingContainer(id);
            await ShippingContainerService.Delete(shippingcontainer);
            return RedirectToAction("Index");
        }     
    }
}

CodeTheWay/CodeTheWay.Web.Ui/Views/ShippingContainer/Create.cshtml
@model CodeTheWay.Web.Ui.Models.ShippingContainer
@*
    ViewData["Title"] = "Index";
*@
<h1>Create</h1>
<form asp-action="Register">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Weight" class="control-label"></label>
        <input asp-for="Weight" class="form-control" />
        <span asp-validation-for="Weight" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Destination" class="control-label"></label>
        <input asp-for="Destination" class="form-control" />
        <span asp-validation-for="Destination" class="text-danger"></span>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index" asp-controller="ShippingContainer">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CodeTheWay/CodeTheWay.Web.Ui/Views/ShippingContainer/Details.cshtml
@model CodeTheWay.Web.Ui.Models.ShippingContainer
@*
    ViewData["Title"] = "Details";
*@
<h1>Details</h1>
<p>Weight:  @Model.Weight</p>
<p>Destination:  @Model.Destination</p>
<div>
    <a asp-action="Index">Back to List</a>
</div>

CodeTheWay/CodeTheWay.Web.Ui/Views/ShippingContainer/Edit.cshtml
@model CodeTheWay.Web.Ui.Models.ShippingContainer
@*
    ViewData["Title"] = "Edit";
*@
<h1>Edit</h1>
<form asp-action="Update">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div id="hidden" class="form-group" display="none">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" value=@Model.Id />
    </div>
    <div class="form-group">
        <label asp-for="Weight" class="control-label"></label>
        <input asp-for="Weight" class="form-control" value=@Model.Weight />
        <span asp-validation-for="Weight" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Destination" class="control-label"></label>
        <input asp-for="Destination" class="form-control" value=@Model.Destination/>
        <span asp-validation-for="Destination" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CodeTheWay/CodeTheWay.Web.Ui/Views/ShippingContainer/Index.cshtml
@model List<CodeTheWay.Web.Ui.Models.ShippingContainer>
@*
    ViewData["Title"] = "Index";
*@
<h1>Index</h1>
    <table class="table table-striped">
        <tr>
            <th>
                Weight
            </th>
            <th>
                Destination
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destination)
                </td>
                <td>
                    <div>
                        <div>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        </div>
                    </div>
                    <div>
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </div>
                    <div>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </div>
                </td>
            </tr>
        }
    </table>
<div>
    <a asp-action="Create">Create a Shipping Container.</a>
</div>